### PR TITLE
Formatted all the files

### PR DESCRIPTION
**Pull request by jakobht**
The files had a mix of tabs and spaces (even in the same file!) - Ran the Visual Studio formatter on all files in the project

### CODE REVIEW

**Comment by jakobht** [comment]
Yeah it's really strange. I reviewed it using VSCode with gitlens and the diff was much more readable, it looks like githubs diff algorithm just breaks.

I would suggest using:
`git diff master -w` 

which diffs with master but ignores whitespace changes. You can then see the few places where the formatter moved a '{' .

**Comment by emiltin** [comment]
sorry, but i think this is too hard to review, and covers too many files. I suggest opening an issue instead, and let the maintainers fix this. (i'm not myself coding on the simulator).

i also see that you're inserting ^M at the end of all line. i don't think we would want this.

**Comment by emiltin** [comment]
maybe it's related to the change of line endings, but i see every line changed even when using diff -m

**Comment by otterdahl** [comment]
We'll close this pull request due to being too hard to review.

**Pull request closed without merging**
