### PR TITLE
For simple value modif, option to considerate updated even if same value.

### PR DESCRIPTION
**Pull request by marcgarba**
When entering new simple value, added option checkbox to select if even same value is considerated as updated.

### CODE REVIEW

**Comment by marcgarba** [comment]
Pehaps another possibility without adding a checkbox in the window, would have been to simply delete the modification test at the end, and just considerate 'updated' (even if same value) when clicking on "OK".
(as it is the case with arrays, whatever the content of items).
But interesting to see that it is a possibility with subscribe, to send an update for some signals uses (even if same value received, interesting to know it)...

**Comment by otterdahl** [comment]
Thank you for the contribution. However, the checks fail. This branch needs to be merged with the 1.0.6 branch in order pass the checks.

**Comment by otterdahl** [comment]
I tested this manually and it looks good. I'm merging this for the upcoming 1.0.7 version

**Comment by marcgarba** [comment]
Thank you to have integrated this small change, which seemed interesting to me!

**Pull request merged**
