### PR TITLE
At startup, disable textbox free SXL version if use SXL from file checked

### PR DESCRIPTION
**Pull request by marcgarba**
Hello,
a very little cosmetic modification.
Best regards.

### CODE REVIEW

**Comment by emiltin** [comment]
there's still a big diff on the ini files: https://github.com/rsmp-nordic/rsmp_simulator/pull/50/files. did you change indentation or line feeds?

**Comment by marcgarba** [comment]
I've downloaded them individually from github view web interface, perhaps I should not have.
At the start I've simpley exluded the ".ini" files from git follow, but it was problematic.

**Comment by emiltin** [comment]
the best is to use git tools to fetch files and push commits. either the command-line tools, or a graphical tool like GitHub Desktop https://desktop.github.com/

**Comment by marcgarba** [comment]
I'm using directly the "Git" menu included in Visual Studio Community, quite convenient.
Git is powerful, but you still have to master everything... not my case for now ! :-(

**Comment by otterdahl** [comment]
Thank you for your contribution.
I think your fix is OK and I'll apply it.

However, there are many files touched in this PR, so I'll add 55ac449750e53f990c32de91f2d302b19c91e50a directly to `master` and I'll close this PR. I recommend using `git revert` to undo any previous commit.

**Pull request closed without merging**
